# Generated by Django 5.2.3 on 2025-06-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='original_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='original_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/'),
        ),
    ]
